import json
from datetime import datetime

def generate_html(host, results, start_port, end_port):
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    severity_badge = {
        "CRITICAL": ("background:#500; color:#fcc;", "CRITICAL"),
        "HIGH":     ("background:#700; color:#fcc;", "HIGH"),
        "MEDIUM":   ("background:#640; color:#fec;", "MEDIUM"),
        "LOW":      ("background:#030; color:#cfc;", "LOW"),
        "Unknown":  ("background:#333; color:#ccc;", "UNKNOWN"),
    }

    port_cards = ""
    for r in results:
        cve_rows = ""
        for cve in r["cves"]:
            style, label = severity_badge.get(cve["severity"], severity_badge["Unknown"])
            cve_rows += f"""
            <tr>
              <td><a href="https://nvd.nist.gov/vuln/detail/{cve['id']}" target="_blank">{cve['id']}</a></td>
              <td><span class="badge" style="{style}">{label}</span></td>
              <td>{cve['score']}</td>
              <td>{cve['description']}</td>
            </tr>"""

        cve_table = f"""
        <table>
          <thead><tr><th>CVE ID</th><th>Severity</th><th>Score</th><th>Description</th></tr></thead>
          <tbody>{cve_rows}</tbody>
        </table>""" if r["cves"] else "<p class='no-cve'>No CVEs found for this service.</p>"

        banner_line = f"<p class='banner'>Banner: {r['banner']}</p>" if r["banner"] else ""

        port_cards += f"""
        <div class="port-card">
          <div class="port-header">
            <span class="port-num">Port {r['port']}</span>
            <span class="service-name">{r['service']}</span>
            <span class="cve-count">{len(r['cves'])} CVE(s)</span>
          </div>
          {banner_line}
          {cve_table}
        </div>"""

    if not results:
        port_cards = "<p style='color:#888;text-align:center;padding:2rem;'>No open ports found.</p>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Scan Report — {host}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }}
    h1 {{ font-size: 1.5rem; color: #58a6ff; margin-bottom: .25rem; }}
    .meta {{ font-size: .85rem; color: #8b949e; margin-bottom: 2rem; }}
    .summary {{ display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }}
    .stat {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1rem 1.5rem; }}
    .stat-num {{ font-size: 2rem; font-weight: 600; color: #58a6ff; }}
    .stat-label {{ font-size: .8rem; color: #8b949e; margin-top: .2rem; }}
    .port-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; margin-bottom: 1.25rem; overflow: hidden; }}
    .port-header {{ display: flex; align-items: center; gap: 1rem; padding: .85rem 1.25rem; background: #1c2128; border-bottom: 1px solid #30363d; }}
    .port-num {{ font-size: 1rem; font-weight: 600; color: #58a6ff; }}
    .service-name {{ font-size: .9rem; color: #c9d1d9; }}
    .cve-count {{ margin-left: auto; font-size: .8rem; color: #8b949e; }}
    .banner {{ font-size: .8rem; color: #8b949e; padding: .5rem 1.25rem; font-family: monospace; border-bottom: 1px solid #30363d; }}
    table {{ width: 100%; border-collapse: collapse; font-size: .85rem; }}
    th {{ text-align: left; padding: .6rem 1rem; color: #8b949e; font-weight: 500; border-bottom: 1px solid #30363d; }}
    td {{ padding: .65rem 1rem; border-bottom: 1px solid #21262d; vertical-align: top; }}
    tr:last-child td {{ border-bottom: none; }}
    td a {{ color: #58a6ff; text-decoration: none; }}
    td a:hover {{ text-decoration: underline; }}
    .badge {{ font-size: .7rem; padding: 2px 8px; border-radius: 12px; font-weight: 600; }}
    .no-cve {{ padding: 1rem 1.25rem; color: #8b949e; font-size: .85rem; }}
    footer {{ text-align: center; font-size: .75rem; color: #444; margin-top: 2rem; }}
  </style>
</head>
<body>
  <h1>Port Scan Report</h1>
  <p class="meta">Target: {host} &nbsp;|&nbsp; Ports {start_port}–{end_port} &nbsp;|&nbsp; {timestamp}</p>
  <div class="summary">
    <div class="stat"><div class="stat-num">{len(results)}</div><div class="stat-label">Open ports</div></div>
    <div class="stat"><div class="stat-num">{sum(len(r['cves']) for r in results)}</div><div class="stat-label">CVEs found</div></div>
    <div class="stat"><div class="stat-num">{end_port - start_port + 1}</div><div class="stat-label">Ports scanned</div></div>
  </div>
  {port_cards}
  <footer>Generated by port-scanner · github.com/ember</footer>
</body>
</html>"""

    filename = f"reports/scan_{host.replace('.','_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    with open(filename, "w") as f:
        f.write(html)

    return filename


def generate_json(host, results, start_port, end_port):
    output = {
        "target": host,
        "ports_scanned": f"{start_port}-{end_port}",
        "timestamp": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        "open_ports": results
    }
    filename = f"reports/scan_{host.replace('.','_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(filename, "w") as f:
        json.dump(output, f, indent=2)
    return filename